services:
  terrareg:
    container_name: "${DOCKER_NAME}_app"
    restart: unless-stopped
    build: .
    depends_on:
      - mysql
      - minio
    env_file:
      - ./.env
    volumes:
      - ./:/app
      # - ~/.ssh/:/root/.ssh/:ro
    ports:
     - 5000:5000
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 5s
      retries: 30
      start_period: 30s
      timeout: 10s

  mysql:
    container_name: "${DOCKER_NAME}_mysql"
    restart: unless-stopped
    image: mariadb:10.11
    volumes:
      - 'mysql:/var/lib/mysql'
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio
    ports:
     - 9000:9000
     - 9001:9001
    restart: always
    env_file:
     - .env
    environment:
      MINIO_ACCESS_KEY: $AWS_ACCESS_KEY_ID
      MINIO_SECRET_KEY: $AWS_SECRET_ACCESS_KEY
    command: server /data --console-address ":9001"
    volumes:
     - 'minio:/data'

  createbucket:
    image: minio/mc
    depends_on:
      - minio
    env_file:
     - .env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add terrareg $AWS_ENDPOINT_URL $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY;
      /usr/bin/mc mb terrareg/$AWS_BUCKET_NAME;
      exit 0;
      "

volumes:
  terrareg:
    driver: local
    name: "${DOCKER_NAME}_app"
  mysql:
    driver: local
    name: "${DOCKER_NAME}_mysql"
  minio:
    driver: local
    name: "${DOCKER_NAME}_s3"
